/*
-- Query: 
-- Date: 2015-12-04 03:12
*/
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (address_id,'street','town','state','zipcode','nearest_intersec','room_no');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (5,'Hoepker','Asheville','North Carolina','28815','E88','213');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (10,'Namekagon','Washington','District of Columbia','20067','E21','312');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (12,'Trailsway','Stockton','California','95298','E7','324');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (20,'Morningstar','Kalamazoo','Michigan','49048','E60','34');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (26,'Beilfuss','Hollywood','Florida','33028','E7','54');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (27,'Katie','Portland','Maine','4109','E7','757');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (32,'Stephen','Santa Barbara','California','93111','E7','53');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (38,'Bartillon','Reading','Pennsylvania','19610','E7','234');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (42,'Ramsey','Dallas','Texas','75205','E7','6535');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (43,'Scoville','Miami','Florida','33185','E60','44');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (57,'Schurz','Prescott','Arizona','86305','E7','876');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (59,'Cordelia','Spartanburg','South Carolina','29305','E7','534');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (60,'Cordelia','Oakland','California','94627','E21','546');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (63,'Cottonwood','Lafayette','Louisiana','70593','E60','753');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (67,'Elmside','Syracuse','New York','13251','E60','45');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (68,'Nobel','Minneapolis','Minnesota','55487','E7','654');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (69,'Dexter','Arlington','Texas','76011','E60','213');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (75,'Luster','New Haven','Connecticut','6538','E7','312');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (79,'Meadow Vale','Lubbock','Texas','79410','E21','324');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (80,'Sutherland','Albuquerque','New Mexico','87110','E60','34');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (82,'Thackeray','Stamford','Connecticut','6905','E88','54');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (87,'Butternut','Houston','Texas','77010','E88','757');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (88,'Caliangt','Kalamazoo','Michigan','49006','E88','53');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (91,'Union','Portland','Oregon','97255','E88','234');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (92,'Ohio','Green Bay','Wisconsin','54313','E88','6535');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (96,'Debra','Billings','Montana','59105','E60','44');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (1,'Green','Charlottesville','Virginia','22903','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (2,'Memorial','Dayton','Ohio','45419','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (3,'Heffernan','South Bend','Indiana','46634','E60','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (4,'Superior','Chicago','Illinois','60609','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (6,'Harper','Honolulu','Hawaii','96815','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (7,'Shoshone','Appleton','Wisconsin','54915','E60','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (8,'Hovde','Oklahoma City','Oklahoma','73190','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (9,'Kings','Orlando','Florida','32868','E60','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (11,'Dorton','Evansville','Indiana','47719','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (13,'Meadow Valley','San Antonio','Texas','78255','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (14,'Huxley','Washington','District of Columbia','20299','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (15,'Starling','Orlando','Florida','32813','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (16,'Fulton','Los Angeles','California','90081','E60','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (17,'Tennessee','Washington','District of Columbia','20220','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (18,'Nelson','Los Angeles','California','90087','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (19,'Fremont','Vero Beach','Florida','32969','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (21,'Fulton','Huntsville','Alabama','35895','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (22,'Burning Wood','Hampton','Virginia','23663','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (23,'International','Denver','Colorado','80204','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (24,'Sloan','Lansing','Michigan','48912','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (25,'Tennessee','Albany','New York','12222','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (28,'Lindbergh','Flushing','New York','11388','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (29,'Springs','Pasadena','California','91186','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (30,'Clemons','Houston','Texas','77050','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (31,'Bunker Hill','Lincoln','Nebraska','68531','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (33,'Luster','Fort Pierce','Florida','34949','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (34,'Randy','Columbus','Ohio','43210','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (35,'Forest Run','Boston','Massachusetts','2208','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (36,'Carey','East Saint Louis','Illinois','62205','E60','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (37,'Hollow Ridge','Richmond','Virginia','23208','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (39,'Brentwood','New York City','New York','10184','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (40,'Hudson','El Paso','Texas','88525','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (41,'Schiller','Atlanta','Georgia','30380','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (44,'Eastlawn','Austin','Texas','78744','E60','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (45,'Meadow Vale','El Paso','Texas','88574','E60','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (46,'Northfield','Fort Wayne','Indiana','46805','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (47,'Cordelia','Shawnee Mission','Kansas','66276','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (48,'Helena','Aurora','Colorado','80045','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (49,'Graedel','Dallas','Texas','75367','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (50,'Stoughton','Las Vegas','Nevada','89120','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (51,'Hudson','Boulder','Colorado','80305','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (52,'Badeau','Honolulu','Hawaii','96845','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (53,'Parkside','Atlanta','Georgia','30323','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (54,'Havey','Nashville','Tennessee','37215','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (55,'Havey','Norfolk','Virginia','23520','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (56,'Summer Ridge','Phoenix','Arizona','85040','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (58,'Glendale','Los Angeles','California','90087','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (61,'Luster','Jamaica','New York','11431','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (62,'Clove','Philadelphia','Pennsylvania','19093','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (64,'Lakeland','Atlanta','Georgia','30316','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (65,'Emmet','Pomona','California','91797','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (66,'Columbus','Washington','District of Columbia','20099','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (70,'Rowland','Tampa','Florida','33620','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (71,'Kinsman','Saint Paul','Minnesota','55188','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (72,'Village','Atlanta','Georgia','30306','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (73,'Maple','San Francisco','California','94142','E88','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (74,'Parkside','Kansas City','Missouri','64187','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (76,'Hoffman','Stockton','California','95210','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (77,'Acker','Miami','Florida','33180','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (78,'Clove','Wilmington','Delaware','19897','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (81,'Aberg','Elizabeth','New Jersey','7208','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (83,'Del Mar','Toledo','Ohio','43666','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (84,'Mitchell','San Antonio','Texas','78291','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (85,'Vera','Newark','Delaware','19714','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (86,'Glendale','Lincoln','Nebraska','68517','E7','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (89,'Northview','Denton','Texas','76210','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (90,'Atwood','Boca Raton','Florida','33499','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (93,'Grasskamp','Albuquerque','New Mexico','87201','E21','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (94,'Pankratz','Oceanside','California','92056','E60','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (95,'Buhler','Indianapolis','Indiana','46278','E60','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (97,'Talmadge','San Antonio','Texas','78255','E60','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (98,'Jenna','Washington','District of Columbia','20260','E60','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (99,'Moose','Buffalo','New York','14263','E60','');
INSERT INTO `address` (`address_id`,`street`,`town`,`state`,`zipcode`,`nearest_intersec`,`room_no`) VALUES (100,'Everett','Fullerton','California','92835','E60','');
