/*
-- Query: 
-- Date: 2015-12-04 03:13
*/
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (optional_info_id,age,'sex','smoker','current_commute',min_cost_comp,max_cost_comp,'preference');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (1,40,'F','YES','CAR POOL',5,10,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (2,20,'M','NO','DRIVE ALONE',20,30,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (3,19,'M','YES','DRIVE ALONE',23,35,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (4,18,'M','NO','OTHERS',12,35,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (5,19,'F','NO','DRIVE ALONE',18,25,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (6,33,'M','NO','CAR POOL',3,5,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (7,22,'F','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (8,22,'M','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (9,45,'F','NO','CAR POOL',4,12,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (10,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (11,34,'F','YES','CAR POOL',5,10,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (12,22,'M','NO','DRIVE ALONE',20,30,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (13,16,'M','YES','DRIVE ALONE',23,35,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (14,55,'M','NO','OTHERS',12,35,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (15,38,'F','NO','DRIVE ALONE',18,25,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (16,39,'M','NO','CAR POOL',3,5,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (17,22,'F','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (18,22,'M','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (19,45,'F','NO','CAR POOL',4,12,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (20,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (21,20,'M','NO','DRIVE ALONE',20,30,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (22,19,'M','YES','DRIVE ALONE',23,35,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (23,18,'M','NO','OTHERS',12,35,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (24,19,'F','NO','DRIVE ALONE',18,25,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (25,33,'M','NO','CAR POOL',3,5,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (26,22,'F','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (27,22,'M','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (28,45,'F','NO','CAR POOL',4,12,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (29,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (30,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (31,34,'F','YES','CAR POOL',5,10,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (32,22,'M','NO','DRIVE ALONE',20,30,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (33,16,'M','YES','DRIVE ALONE',23,35,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (34,55,'M','NO','OTHERS',12,35,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (35,38,'F','NO','DRIVE ALONE',18,25,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (36,39,'M','NO','CAR POOL',3,5,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (37,22,'F','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (38,22,'M','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (39,45,'F','NO','CAR POOL',4,12,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (40,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (41,20,'M','NO','DRIVE ALONE',20,30,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (42,19,'M','YES','DRIVE ALONE',23,35,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (43,18,'M','NO','OTHERS',12,35,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (44,19,'F','NO','DRIVE ALONE',18,25,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (45,33,'M','NO','CAR POOL',3,5,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (46,22,'F','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (47,22,'M','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (48,45,'F','NO','CAR POOL',4,12,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (49,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (50,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (51,34,'F','YES','CAR POOL',5,10,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (52,22,'M','NO','DRIVE ALONE',20,30,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (53,16,'M','YES','DRIVE ALONE',23,35,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (54,55,'M','NO','OTHERS',12,35,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (55,38,'F','NO','DRIVE ALONE',18,25,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (56,39,'M','NO','CAR POOL',3,5,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (57,22,'F','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (58,22,'M','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (59,45,'F','NO','CAR POOL',4,12,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (60,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (61,20,'M','NO','DRIVE ALONE',20,30,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (62,19,'M','YES','DRIVE ALONE',23,35,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (63,18,'M','NO','OTHERS',12,35,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (64,19,'F','NO','DRIVE ALONE',18,25,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (65,33,'M','NO','CAR POOL',3,5,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (66,22,'F','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (67,22,'M','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (68,45,'F','NO','CAR POOL',4,12,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (69,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (70,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (71,34,'F','YES','CAR POOL',5,10,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (72,22,'M','NO','DRIVE ALONE',20,30,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (73,16,'M','YES','DRIVE ALONE',23,35,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (74,55,'M','NO','OTHERS',12,35,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (75,38,'F','NO','DRIVE ALONE',18,25,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (76,39,'M','NO','CAR POOL',3,5,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (77,22,'F','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (78,22,'M','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (79,45,'F','NO','CAR POOL',4,12,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (80,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (81,20,'M','NO','DRIVE ALONE',20,30,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (82,19,'M','YES','DRIVE ALONE',23,35,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (83,18,'M','NO','OTHERS',12,35,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (84,19,'F','NO','DRIVE ALONE',18,25,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (85,33,'M','NO','CAR POOL',3,5,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (86,22,'F','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (87,22,'M','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (88,45,'F','NO','CAR POOL',4,12,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (89,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (90,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (91,34,'F','YES','CAR POOL',5,10,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (92,22,'M','NO','DRIVE ALONE',20,30,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (93,16,'M','YES','DRIVE ALONE',23,35,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (94,55,'M','NO','OTHERS',12,35,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (95,38,'F','NO','DRIVE ALONE',18,25,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (96,39,'M','NO','CAR POOL',3,5,'PASSENGER ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (97,22,'F','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (98,22,'M','YES','BUS',6,12,'SHARE DRIVING');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (99,45,'F','NO','CAR POOL',4,12,'DRIVE ONLY');
INSERT INTO `user_optional_info` (`optional_info_id`,`age`,`sex`,`smoker`,`current_commute`,`min_cost_comp`,`max_cost_comp`,`preference`) VALUES (100,20,'F','YES','TRAIN',8,15,'SHARE DRIVING');
